---
name: CI

on:
  push:
    branches:
      - next
  pull_request:
    branches:
      - next

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    strategy:
      matrix:
        node-version: [14.16, 16.11, 17]
    name: Use Node.js ${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: yarn install
        run: yarn --immutable
      - name: Linting
        run: yarn lint
      - name: Building
        run: yarn workspace @nuxt/i18n build
      - name: Testing
        run: yarn test
